name: postgres_adapter
version: 0.0.6
author: Axel Christ <adracus@gmail.com>
description: A pub package
homepage: https://github.com/Adracus/PostgresAdapter
dependencies:
  activerecord:
    git: https://github.com/Adracus/ActiveRecord.git
    version: any
  logging: '>=0.9.1+1 <0.10.0'
  postgresql: '>=0.2.13 <0.3.0'
dev_dependencies:
  args: any
  unittest: any
